### ISSUE TITLE
DataManager.match_data() Error

### ISSUE THREAD

**Issue by apdunn2** [mdomanski-usgs/linearmodel#1]
There is a potential issue with the match_data() method in the DataManager class. If the surrogate data begins after the constituent data, an error is raised.

KeyError: Timestamp('2015-10-05 08:50:00')     #Beginning of Constituent Data Timestamp

**Comment by mdomanski-usgs** [comment]
pandas.Index.get_loc() raises a KeyError if the key is outside of the specified tolerance. DataManager.get_variable_observation() now returns NaN if a KeyError is raised by pandas.Index.get_loc().

Issue closed.
